services:
  provider:
    image: connector
    platform: linux/amd64
    container_name: edc-provider
    ports:
      - "19191:19191"
      - "19193:19193"
      - "19194:19194"
      - "19291:19291"
      - "19192:19192"
      - "19195:19195"

    volumes:
      - ./resources/configuration:/app/configuration

    networks:
      - edc-network

networks:
  edc-network:
    external: true